interface basicData {
  [key: string]: string | number;
}
export const exchData: basicData = {
  A: "NYSE MKT",
  B: "NASDAQ OMX BX",
  C: "National Stock Exchange",
  D: "Market Independent (Generated by Nasdaq SIP)",
  E: "Mutual Funds/Money Markets (NASDAQ)",
  F: "International Securities Exchange",
  J: "Direct Edge A",
  K: "Direct Edge X",
  I: "International Securities Exchange",
  L: "Long Term Stock Exchange",
  M: "Chicago Stock Exchange",
  N: "NYSE",
  P: "NYSE Arca",
  Q: "NASDAQ OMX",
  S: "NASDAQ Small Cap",
  T: "NASDAQ Int",
  U: "OTCBB",
  V: "OTC other",
  W: "CBOE",
  X: "NASDAQ OMX PSX",
  G: "GLOBEX",
  Y: "BATS Y-Exchange",
  Z: "BATS",
};
